app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

vv/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from app.views import upload_excel,excel_data
from app.views import upload_excel,marksheet,respones
from app import views
from app.views import send_rank_emails



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('special/', views.special, name='special'),
    path('app/', include('app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('upload_excel/', upload_excel, name='upload_excel'),
    path('result/', excel_data, name='view_excel'),
    path('marksheet/', marksheet, name='marksheet'),
    path('respones/', respones, name='respones'),
    path('analysis-results/', views.analyze_data, name='analyze_data'),
    path('send-rank-emails/', send_rank_emails, name='send_rank_emails'),

   ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/analysis_form.html
{#<form method="post" action="{% url 'analyze_data' %}">#}
{#  {% csrf_token %}#}
{#  {{ form.as_p }}#}
{#  <button type="submit">Analyze Data</button>#}
{#</form>#}



<!DOCTYPE html>
<html>
<head>
  <title> analyze form</title>
<style>
  div{
  text-align: center;
  padding:100px;
  <!--box-shadow: 0 0 20px rgba(0, 0, 0, 0.15); -->
  }
  .indiv1{
  width:25%;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
  margin-left:200px;
  }
  .botton{
   padding: 10px 22px;
   box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
   border-radius:7px;
   border:none;
   background-color:gray;
   color:white;

   }
</style>
</head>
<body>
<div>
<div class="indiv1">
  <br>
	<form method="post" action="{% url 'analyze_data' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<br>
		<button class="botton" type="submit">Analyze Data</button>
	</form>
  </div>
 </div>
</body>
</html>

templates/app/analysis_results.html
<!DOCTYPE html>
<html>
<head>
    <title>Analysis Results</title>
    <style>
        a:link, a:visited {
  background-color: white;
  color: black;
  border: 1px;
  border-radius:7px;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}
a:hover, a:active {
  background-color: gray;
  color: white;
}
    </style>
</head>
<body>
    {% if matching_files %}
{#        <h3>Matching Files:</h3>#}
{#        <ul>#}
{#            {% for file in matching_files %}#}
{#                <li>{{ file.id }}</li>#}
{#            {% endfor %}#}
{#        </ul>#}
        <img src="/static/images1/chart.png" alt="Chart">
        <span><h3>note:exam file id is exam number</h3></span>
    {% endif %}
<hr>
    {% if non_matching_files %}
        <h3><center>NOTE: absent in exam.</center></h3>
        <ul>
            {% for file in non_matching_files %}
                <li>Absent exam File ID: {{ file.id }}</li>
            {% endfor %}
        </ul>
    {% endif %}
<h2><center><a href="{% url 'profile' %}"> click here for profile</a></center></h2>
</body>
</html>

templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">FITJEE</a></li>
          <li><a class="navbar-link" href="{% url 'app:register' %}">Register</a></li>
        <li><a class="navbar-link" href="/admin/">ADMIN</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'app:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/app/excel_form.html
{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#  <title>Excel Form</title>#}
{#</head>#}
{#<body>#}
{#  <h1>Enter Enrolment number</h1>#}
{#  <form method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button type="submit">Submit</button>#}
{#  </form>#}
{#</body>#}
{#</html>#}


<!DOCTYPE html>
<html>
<head>
  <title>Excel Form</title>
<style>
  div{
  text-align: center;
  padding:100px;
  <!--box-shadow: 0 0 20px rgba(0, 0, 0, 0.15); -->
  }
  .indiv1{
  width:25%;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
  margin-left:200px;
  }
  .botton{
   padding: 15px 32px;
   box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
   border-radius:7px;
   border:none;
   background-color:gray;
   color:white;
   }
</style>
</head>
<body>
<div>
<div class="indiv1">
  <h2>Enter Enrolment number</h2>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="botton" type="submit">Submit</button>
  </form>
  </div>
 </div>
</body>
</html>

templates/app/index.html
{% extends "app/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    {% if user.is_authenticated %}
        <h1>Welcome back {{ user.username }}  !</h1>
        <a href="{% url 'profile' %}"> click here for profile</a>
    {% else %}
        <h1>Welcome!</h1>
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="">
              {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/app/marksheet.html
{#{% block content %}#}
{#    <h1>student mark_sheet</h1>#}
{#    {{ combined_data|safe }}#}
{#{% endblock %}#}
{#{% block content %}#}
{#    <h1>student result and respones</h1>#}
{#    <table>#}
{#      <thead>#}
{#        <tr>#}
{#          <th>enrolment_number</th>#}
{#            <th>Batch</th>#}
{#          <th>Student_Name</th>#}
{#            <th>RANK</th>#}
{#            <th>MATHS</th>#}
{#            <th>PHY</th>#}
{#            <th>CHE</th>#}
{#        </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#      {% for index, row in combined_data.iterrows %}#}
{#        <tr>#}
{#        <td>{{ row.enrolment_number }}</td>#}
{#            <td>{{ row.Batch }}</td>#}
{#             <td>{{ row.Student_Name }}</td>#}
{#            <td>{{ row.RANK }}</td>#}
{#            <td>{{ row.MATHS }}</td>#}
{#            <td>{{ row.PHY }}</td>#}
{#            <td>{{ row.CHE }}</td>#}
{#               </tr>#}
{##}
{#      {% endfor %}#}
{#      </tbody>#}
{#    </table>#}
{#{% endblock %}#}
<!DOCTYPE html>
<html>
<head>
    <title>View Excel Data</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        .error-message {
            color: red;
        }
        a:link, a:visited {
  background-color: white;
  color: black;
  border: 1px;
  border-radius:7px;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}
a:hover, a:active {
  background-color: gray;
  color: white;
}
    </style>
</head>
<body>
    {% if matching_data_found %}
        <table>
            <thead>
                <tr>
                    <th>File ID</th>
                    <th> DATE </th>
                    <th>Enrolment Number</th>
                    <th>pattern</th>
                    <th>RANK</th>
                    <th>MATHS</th>
                    <th>PHY</th>
                    <th>CHE</th>
                    <!-- Add other columns as needed -->
                </tr>
            </thead>
            <tbody>
                {% for data in data_list %}
                    {% for _, row in data.iterrows %}
                        <tr>
                            <td>{{ row.File_ID }}</td>
                            <td>{{ row.Timestamp }}</td>
                            <td>{{ row.enrolment_number }}</td>
                            <td>JEEM</td>
                            <td>{{ row.RANK }}</td>
                            <td>{{ row.MATHS }}</td>
                            <td>{{ row.PHY }}</td>
                            <td>{{ row.CHE }}</td>
                            <!-- Add other columns as needed -->
                        </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
    {% if error_messages %}
        <h2>ABSENT</h2>
        <span><h3>NOTE: exam File_ID == exam number</h3></span>
        <ul>
            {% for error_message in error_messages %}
                <li class="error-message">{{ error_message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
<h2><center><a href="{% url 'profile' %}"> click here for profile</a></center></h2>
</body>
</html>

templates/app/marksheet_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
                div{
  text-align: center;
  padding:100px;
  <!--box-shadow: 0 0 20px rgba(0, 0, 0, 0.15); -->
  }
  .indiv1{
  width:25%;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
  margin-left:200px;
  }
  .botton{
   padding: 10px 22px;
   box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
   border-radius:7px;
   border:none;
   background-color:gray;
   color:white;

   }

    </style>
</head>
<body>
<div>
<div class="indiv1">
    <h1> view marksheet</h1>

    <form method="post" action="{% url 'marksheet' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="botton" type="submit"> SUBMIT </button>
    </form>
</div>
</div>
</body>
</html>

templates/app/profile.html
{% extends "app/base.html" %}
{% block body_block %}
<style>
.profile{
    text-align: center;
    {#border:1px Solid Maroon;#}
    float:right;
    width:40%;
    height:330px;
    /*margin:1px;*/
    margin-top: 5px;
    box-shadow:0px 8px 10px #d3d3d3;
    padding-top: 50px;
}
.profile1{
    text-align: center;
    {#border:1px Solid Maroon;#}
    float:left;
    width:20%;
    height:330px;
    margin-top:10px;
    box-shadow:0px 8px 10px #d3d3d3;
    padding-top: 50px;
    margin-left: 80px;
}

img{
   /* border:1px dotted blue;*/
    width:60%;
    height:150px;
    margin:1px;
    box-shadow:0px 8px 10px #d3d3d3;
    border-radius:50%;
}

a:link{
text-decoration:none;
}
a:link, a:visited {
  background-color: white;
  color: black;
  border: 1px;
  border-radius:7px;
  width:90%;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}
a:hover, a:active {
  background-color: gray;
  color: white;
}

</style>

{% csrf_token %}
<div class="profile">
<img src="/static/images/profile.png" alt="profile.png" /><br/>
    <h3>NAME : {{ user.username }}</h3></br>
    <h3>EMAIL: {{ user.email }}</h3>
</div>
    <span><h3>CHECK HERE FOR RESULT:</h3></span>
<div class="profile1">
	     <a href="/result/">RESULT</a></br></br>
        <a href="/respones/">RESPONES_sheet</a></br></br>
        <a href="/marksheet/">MARKS_sheet</a></br></br>
        <a href="/analysis-results/">ANALYSIS</a></br></br>
</div>
{% endblock %}

templates/app/registration.html
{% extends "app/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
      <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html>#}
{#  <head>#}
{#    <meta charset="utf-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <title>Signup Page| FIITJEE </title>#}
{#    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">#}
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">#}
{#    <link rel="website icon" href="../../static/img/website icon.png">#}
{#    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>#}
{#    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>#}
{##}
{#      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">#}
{#    <style>#}
{#      *{#}
{#        font-family: 'poppins', sans-serif;#}
{#      }#}
{#      .navbar.is-white{#}
{#          background-color: white;#}
{#          border-radius: 6px;#}
{#      }#}
{#      .hero.is-dark{#}
{#          background-color: white;#}
{#      }#}
{#      .field .button{#}
{#          margin-left: 100px;#}
{#          margin-top: 10px;#}
{#          margin-bottom: 10px;#}
{#      }#}
{#      .field{#}
{#          color: black;#}
{#          font-size: 20px;#}
{#      }#}
{#      .hero.is-dark a:not(.button):not(.dropdown-item):not(.tag):not(.pagination-link.is-current), .hero.is-dark strong {#}
{#         color:#007bff;#}
{#        }#}
{#      .field a {#}
{#        text-decoration: none;#}
{#        background-color: transparent;#}
{#          font-size: 18px;#}
{#          margin-bottom: 30px;#}
{#    }#}
{#      .field a:hover{#}
{#          text-decoration: underline;#}
{##}
{#      }#}
{#      .navbar-item img{#}
{#          border-radius: 5px;#}
{#          box-shadow: 2px 2px 5px #999;#}
{#          height: 100px;#}
{#          margin-top: 10px;#}
{#          margin-left: 10px;#}
{##}
{#      }#}
{#      .hero-body{#}
{#          margin-top: -40px;#}
{#      }#}
{#      .box {#}
{#        background-color: #fff;#}
{#        border-radius: 6px;#}
{#        box-shadow: 0 0.5em 1em -0.125em rgba(10,10,10,.1), 0 0 0 1px rgba(10,10,10,.02);#}
{#        color: #4a4a4a;#}
{#        display: block;#}
{#        padding: 1.25rem;#}
{#        width: 375px;#}
{#        margin: auto;#}
{#        margin-bottom: 70px;#}
{#        margin-left: -65px;#}
{#    }#}
{#      .field span{#}
{#          font-size: 16px;#}
{#          margin-left: 60px;#}
{##}
{#      }#}
{#      .field .button {#}
{#        margin-left: 120px;#}
{#        margin-top: 10px;#}
{#        margin-bottom: 10px;#}
{#    }#}
{#    </style>#}
{##}
{#  </head>#}
{#  <body>#}
{#    <nav class="navbar is-white" role="navigation" aria-label="main navigation">#}
{#      <div class="navbar-brand">#}
{#        <a class="navbar-item" href="/">#}
{#          <img src="../../static/img/logo.png" alt="" width="100px" >#}
{#        </a>#}
{#      </div>#}
{#    </nav>#}
{##}
{#    <section class="hero is-dark is-fullheight">#}
{#      <div class="hero-body">#}
{#        <div class="container">#}
{#          <div class="columns is-centered">#}
{#            <div class="column is-5-tablet is-4-desktop is-3-widescreen">#}
{#                {% if registered %}#}
{#                      <h1>Thank you for registering!</h1>#}
{#                        {% else %}#}
{#                        <h1>Register Here</h1>#}
{#              <form method="POST" action="." class="box">#}
{#                {% csrf_token %}#}
{##}
{#                <h1 class="has-text-centered mb-5 is-size-3 ">Signup</h1>#}
{##}
{#                <div class="form-group">#}
{#                <label for="exampleInputEmail1">username</label>#}
{#                    {{ form.username }}#}
{#              </div>#}
{##}
{#              <div class="form-group">#}
{#                <label for="exampleInputEmail1">Email</label>#}
{#                    {{ form.email}}#}
{#              </div>#}
{##}
{#                <div class="form-group">#}
{#                <label for="exampleInputEmail1">Password</label>#}
{#                    {{ form.password1}}#}
{#              </div>#}
{##}
{#               <div class="form-group">#}
{#                <label for="exampleInputEmail1">Confirm Password</label>#}
{#                    {{ form.password2}}#}
{#              </div>#}
{##}
{#                <div class="field">#}
{#                  <button class="button is-success" type=submit>#}
{#                    register#}
{#                  </button>#}
{#                </div>#}
{#                <div class="field">#}
{#                    <span>Already registered ?</span> <a href="{% url 'app:user_login' %}">Login</a>#}
{#                </div>#}
{##}
{#              </form>#}
{#                {% endif %}#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </section>#}
{# </body>#}
{#</html>#}

templates/app/upload_excel.html
  <h1>Upload Excel File</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

templates/app/view_excel.html
{#{% block content %}#}
{#    <h1>student result and respones</h1>#}
{#    {{ data|safe }}#}
{#{% endblock %}#}
{#{% block content %}#}
{#    <h1>student result </h1>#}
{#    <table border="2" >#}
{#      <thead>#}
{#        <tr>#}
{#            <th>Timestamp</th>#}
{#            <th>enrolment_number</th>#}
{#            <th>Batch</th>#}
{#            <th>Student_Name</th>#}
{#            <th>RANK</th>#}
{#            <th>MATHS</th>#}
{#            <th>PHY</th>#}
{#            <th>CHE</th>#}
{#            <th>TOTAL</th>#}
{#        </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#      {% for index, row in data.iterrows %}#}
{#        <tr><td>{{ row.Timestamp }}</td>#}
{#         <td>{{ row.enrolment_number }}</td>#}
{#         <td>{{ row.Batch }}</td>#}
{#         <td>{{ row.Student_Name }}</td>#}
{#        <td>{{ row.RANK }}</td>#}
{#        <td>{{ row.MATHS }}</td>#}
{#        <td>{{ row.PHY }}</td>#}
{#        <td>{{ row.CHE }}</td>#}
{#        <td>{{ row.TOTAL }}</td>#}
{#        </tr>#}
{#      {% endfor %}#}
{#      </tbody>#}
{#    </table>#}
{#{% endblock %}#}
{##}

{% block content %}
<head>
	<style>
.styled-table {
    border-collapse: collapse;
    margin: 25px 0;
    font-size: 0.9em;
    font-family: sans-serif;
    min-width: 400px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
.styled-table thead tr {
    background-color: #009879;
    color: #ffffff;
    text-align: center;
}
.styled-table th,
.styled-table td {
    padding: 12px 15px;
    text-align: center;
}
.styled-table tbody tr {
    border-bottom: 1px solid #dddddd;
}
.styled-table tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
}

.styled-table tbody tr:last-of-type {
    border-bottom: 2px solid #009879;
}


.styled-table tbody tr.active-row {
    font-weight: bold;
    color: #009879;
}
div{
     padding-left:10px;
}
h2{
color: white;
    text-align: center;
	font-type :  bolder ;
	}

a:link, a:visited {
  background-color: white;
  color: black;
  border: 1px;
  border-radius:7px;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}
a:hover, a:active {
  background-color: gray;
  color: white;
}

</style>
</head>
<body>
<h1><center>student result <center></h1>
<div id="div1">
    <div id="div2">
        <div class="indiv1">
            <table  class="styled-table" >
            <thead>
                <tr>
                    <th><h2>Timestamp</h2></th>
                    <th><h2>enrolment_number</h2></th>
                    <th><h2>Batch</h2></th>
                    <th><h2>Student_Name</h2></th>
                </tr>
            </thead>
                <tbody>
                    {% for index, row in data.iterrows %}
                        <tr>
                            <td><h3>{{ row.Timestamp }}</h3></td>
                             <td><h3>{{ row.enrolment_number }}</h3></td>
                             <td><h3>{{ row.Batch }}</h3></td>
                             <td><h3>{{ row.Student_Name }}</h3></td>

                        </tr>
                    {% endfor %}
                </tbody>
             </table>
        </div>
        <div class="indiv2">
            <table class="styled-table" >
            <thead>
                <tr>
                    <th><h2>RANK</h2></th>
                </tr>
            </thead>
                <tbody>
                    {% for index, row in data.iterrows %}
                        <tr>
                            <td><h3>{{ row.RANK }}</h3></td>
                        </tr>
                    {% endfor %}
                </tbody>
             </table>
        </div>
        <div class="indiv">
            <table class="styled-table" >
            <thead>
                <tr>
                    <th><h2>TOTAL MARKS</h2></th>
                </tr>
            </thead>
                <tbody>
                    {% for index, row in data.iterrows %}
                        <tr>
                            <td><h3>{{ row.TOTAL }}</h3></td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        <div class="indiv4">
            <table class="styled-table" >
            <thead>
                <tr>
                    <th><h2>MATHS</h2></th>
                </tr>
            </thead>
                <tbody>
                    {% for index, row in data.iterrows %}
                        <tr>
                            <td><h3>{{ row.MATHS }}</h3></td>
                        </tr>
                    {% endfor %}
                </tbody>
             </table>

        </div>
        <div class="indiv4">

            <table class="styled-table" >
            <thead>
                <tr>
                    <th><h2>PHY</h2></th>
                </tr>
            </thead>
                <tbody>
                    {% for index, row in data.iterrows %}
                        <tr>
                            <td><h3>{{ row.PHY }}</h3></td>
                        </tr>
                    {% endfor %}
                </tbody>
             </table>

        </div>
        <div class="indiv4">
            <table class="styled-table" >
            <thead>
                <tr>
                    <th><h2>CHE</h2></th>
                </tr>
            </thead>
                <tbody>
                    {% for index, row in data.iterrows %}
                        <tr>
                            <td><h3>{{ row.CHE }}</h3></td>
                        </tr>
                    {% endfor %}
                </tbody>
             </table>
        </div>
    </div>
</div>
<h2><center><a href="{% url 'profile' %}"> click here for profile</a></center></h2>
</body>
{% endblock %}